sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
git:
  depth: 3
node_js:
  - "8"
install:
  - bundle install
  - npm install
script:
  - npm run compile
deploy:
  provider: pages
  skip-cleanup: true
  github-url: https://jeaster12.github.io/cupcake-docs/
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
cache:
  directories:
    - node_modules
    - vendor/bundle
