# Welcome to Cupcake Docs
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
destination:    ./dist
port:           5000
baseurl:        ""
# url:            "https://pages.code.ipreo.com/Ipreo/cupcake-docs"
encoding:       UTF-8

# Build settings
markdown: kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

sass:
    sass_dir: ./assets/scss

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - .git/
  - .github/
  - .sass-cache/
  - js/
  - vendor/
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - template.hbs

# Social
title:              Cupcake
description:        "The Ipreo Design System Responsive, flex-enabled, and fully modular."

# Custom variables
current_version:      1.4.6 
docs_version:         1.0
repo:                 "https://code.ipreo.com/Ipreo/cupcake"
slack:                "https://ipreo.slack.com/messages/C0T3KNMK7/"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
  jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"


collections_dir: content

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      weight: 100
  # _patterns defaults
  - scope:
      path: ""
      type: patterns
    values:
        group: patterns
        category: patterns
  # _elements defaults
  - scope:
      path: ""
      type: elements
    values:
        group: elements
        category: elements
  # _getting-started defaults
  - scope:
      path: ""
      type: getting-started
    values:
        group: getting-started
        category: getting-started
  # _posts defaults
  - scope:
      path: ""
      type: posts
    values:
        layout: "post"
        group: posts
        category: posts             

collections:
  elements:
    output: true
    permalink: /elements/:path/
  patterns:
    output: true
    permalink: /patterns/:path/ 
  getting-started:
    output: true
    permalink: /getting-started/:path/
